version: '3.1'
services:
    nginx:
## pull nginx:latest
        image: nginx:latest
## name it nginx
        container_name: nexus_nginx
## make sure nexus is first
        depends_on:
            - nexus
## mapp our conf over default
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
## internal network
        networks:
            - nexus-net
## forward from docker host 80->80
        ports:
            - 80:80
    nexus:
## build nexus base on Dockerfile
        build:
            context: ./
            dockerfile: Dockerfile
## name it nexus tag 0.0.1
        image: nexus:0.0.1
        container_name: nexus
## a means to overload the application code during runtime
        #volumes:
        #  - ./apps:/opt/apps/
## internal network
        networks:
            nexus-net:
## ref name in nginx.conf nexus-app
                aliases:
                    - nexus-app
## forward from docker host 8080->5000
## only really neeed for debug, nginx will proxy to 5000 direct
        #ports:
        #    - 8080:5000
##internal network
networks:
    nexus-net:
